name: nmbim-env
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - botocore
  - fsspec
  - s3fs
  - geopandas
  - geopandas-base
  - h5py
  - numpy
  - pandas
  - python
  - scipy
  - pip:
      - git+https://git@github.com/MAAP-Project/maap-py@v4.0.0
