name: nmbim-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip=23.3.1

  - click=8.1.7
  - fsspec
  - geopandas
  - h5py=3.11.0
  - matplotlib=3.9.2
  - numpy=2.1.1
  - scipy=1.14.1
  - s3fs
  - botocore=1.34.157
  - aiobotocore
  - boto3
  - backoff

  - pip:
      - git+https://git@github.com/MAAP-Project/maap-py@v4.0.0
      - pyyaml
