# Configuration for GEDI waveform processing

filters:
  temporal:
    time_start: "2019-04-01T00:00:00Z"
    time_end: "2020-03-31T23:59:59Z"

  flag: null

  modes: null

  landcover: null

  spatial:
    file_path: "/path/to/your/polygon/file.gpkg"
    waveform_crs: "EPSG:4326"
