# Configuration for GEDI waveform processing
filters:
  # Filter out waveforms with a low quality flag
  flag: {}

  # Filter out waveforms with no modes identified
  modes:
    min_modes: 1

  # Spatial and temporal parameters provided at runtime
  spatial: {}

  temporal: {}
  
