# Filter configuration for GEDI waveform processing

# Temporal filter
temporal:
  time_start: "2019-04-01T00:00:00Z"
  time_end: "2020-03-31T23:59:59Z"

# Flag filter (no additional parameters needed)
flag: null

# Modes filter (no additional parameters needed)
modes: null

# Landcover filter (no additional parameters needed)
landcover: null

# Spatial filter
spatial:
  file_path: "/path/to/your/polygon/file.gpkg"
  waveform_crs: "EPSG:4326"
