#########################################################
# Configuration file for NMBIM GEDI waveform processing #
#########################################################

# Define the filters to be applied to the waveforms

filters:
  flag: {}
  modes:
    min_modes: 1
  spatial: {}
  temporal: {}
  plausible_ground:
    window_start: 0.1
    window_end: 0.9
  ground_to_top:
    min_height: 5

# Define the processing pipeline

# Each step in the pipeline includes the name of the function within the
# `algorithms` module to be applied (alg_fun), directions for how to
# find the function arguments within a Waveform object (input_map),
# the path within the Waveform object to save the output
# (output_path), and any additional parameters needed by the function
# (params). {} indicates that no additional parameters are needed.

processing_pipeline:
  # Calculate height array
  height:
    alg_fun: calc_height
    input_map:
      wf: raw/wf
      elev_top: raw/elev/top
      elev_bottom: raw/elev/bottom
      elev_ground: raw/elev/ground
    output_path: processed/ht
    params: {}
  # Calculate height increment value
  calc_dz:
    alg_fun: calc_dz
    input_map:
      ht: processed/ht
    output_path: processed/dz
    params: {}
  # Remove signal noise level specified in L1B file
  remove_initial_noise:
    alg_fun: remove_noise
    input_map:
      wf: raw/wf
      mean_noise: raw/mean_noise
    output_path: processed/wf_noise_removed
    params: {}
  # Apply Gaussian smoothing
  smooth:
    alg_fun: smooth_waveform
    input_map:
      wf: processed/wf_noise_removed
    output_path: processed/wf_noise_removed_smooth
    params:
      sd: 8
  # Identify vegetation and ground segments
  segment:
    alg_fun: separate_veg_ground
    input_map:
      wf: processed/wf_noise_removed_smooth
      ht: processed/ht
      dz: processed/dz
      rh: raw/rh
    params:
      min_veg_bottom: 5
      max_veg_bottom: 15
      veg_buffer: 5
      noise_ratio: 2
    output_path: processed/veg_ground_sep
  # Calculate residual noise level above canopy and below ground
  calc_resid_noise:
    alg_fun: calc_noise
    input_map:
      wf: processed/wf_noise_removed_smooth
      veg_top: processed/veg_ground_sep/veg_top
      ground_bottom: processed/veg_ground_sep/ground_bottom
      ht: processed/ht
    output_path: processed/residual_noise
    params:
      noise_ratio: 2
  # Remove residual noise level
  remove_resid_noise:
    alg_fun: remove_noise
    input_map:
      wf: processed/wf_noise_removed_smooth
      mean_noise: processed/residual_noise
    output_path: processed/wf_all_noise_removed
    params: {}
  # For plotting, replicate noise removal and scaling for raw waveform 
  remove_resid_noise_raw:
    alg_fun: remove_noise
    input_map:
      wf: processed/wf_noise_removed
      mean_noise: processed/residual_noise
    output_path: processed/wf_noise_removed_raw
    params: {}
  scale_raw:
    alg_fun: scale_raw_wf
    input_map:
      wf_raw: processed/wf_noise_removed_raw
      wf_smooth: processed/wf_all_noise_removed
      dz: processed/dz
    output_path: processed/wf_raw_scaled
    params: {}
  # Normalize noise-removed waveform
  normalize:
    alg_fun: normalize_waveform
    input_map:
      wf: processed/wf_all_noise_removed
    output_path: processed/wf_norm
    params: {}
  # Calculate change in gap probability per height unit
  dp_dz:
    alg_fun: calc_dp_dz
    input_map:
      wf: processed/wf_norm
      dz: processed/dz
    output_path: processed/dp_dz
    params: {}
  # Generate synthetic ground return
  ground_return:
    alg_fun: create_ground_return
    input_map:
      wf: processed/dp_dz
      ht: processed/ht
      ground_return_max_height: processed/veg_ground_sep/ground_bottom
    output_path: processed/ground_return
    params:
      sd_ratio: 0.25
  # Remove synthetic ground return and truncuate to isolate vegetation
  isolate_veg:
    alg_fun: isolate_vegetation
    input_map:
      wf: processed/dp_dz
      ht: processed/ht
      veg_top: processed/veg_ground_sep/veg_top
      ground_return: processed/ground_return
    output_path: processed/dp_dz_veg_only
    params: {}
  # Select final allometric parameters (raster if available, default if not)
  select_hse:
    alg_fun: select_parameter
    input_map:
      default_value: metadata/parameters/default_hse
      raster_value: metadata/parameters/raster_hse
    output_path: metadata/parameters/hse
    params: {}
  select_k_allom:
    alg_fun: select_parameter
    input_map:
      default_value: metadata/parameters/default_k_allom
      raster_value: metadata/parameters/raster_k_allom
    output_path: metadata/parameters/k_allom
    params: {}
  # Calculate the biomass index
  calc_biwf:
    alg_fun: calc_biomass_index
    input_map:
      dp_dz: processed/dp_dz_veg_only
      dz: processed/dz
      ht: processed/ht
      n_modes: metadata/modes/num_modes
      hse: metadata/parameters/hse
    output_path: results/biomass_index
    params: {}
  calc_adj_biomass_index:
    alg_fun: calc_adj_biomass_index
    input_map:
      biomass_index: results/biomass_index
      k_allom: metadata/parameters/k_allom
    output_path: results/adj_biomass_index
    params: {}
